### PR TITLE
Install codecov for travis build

### PR DESCRIPTION
**Pull request by mingfeng**
no refs

### CODE REVIEW

**Comment by mingfeng** [comment]
@frwickst Let's give it a try

**Comment by frwickst** [comment]
@mingfeng Only one of the commits are needed (first one can be discarded)

**Comment by mingfeng** [comment]
@frwickst Tried to test if it works as separate commits make it easier to revert changes. I'll merge the commits now.

**Comment by frwickst** [comment]
Let's hope that this works now, it should 😄

**Pull request merged**
